### ISSUE TITLE
\frenchspacing for variable monotype font

### ISSUE THREAD

**Issue by uliska** [davidcarlisle/dpctex#10]
Hi David,

I shared your new package on the lilypond-user list (http://lists.gnu.org/archive/html/lilypond-user/2018-02/msg00426.html), and apart from very interested feedback a discussion arose about whether typewriter fonts should have double spaces after punctuation.

There was no definite conclusion but it seems that in some languages/cultures two spaces are required after the fullstop while in others only one is to be used.

I would suggest to make the package behave similarly to regular typesetting with LaTeX: by default print two spaces, and when `\frenchspacing` is active print only one.

**Comment by davidcarlisle** [comment]
I guess so... the package should force monospace font dimensions anyway, effectively like:

```

\documentclass{article}

\usepackage{typewriter}

\begin{document}

\ttfamily
\fontdimen6\font=\fontcharwd\font`x
\fontdimen2\font=\fontdimen6\font
\fontdimen7\font=\fontdimen6\font



a..bb

a. b


\frenchspacing

a. b

\nonfrenchspacing

a. b

\end{document}
```

I'll push those fontdimen settings in to the package at some point.
