### ISSUE TITLE
Define font from document

### ISSUE THREAD

**Issue by Shane-Brandes** [davidcarlisle/dpctex#11]
Hi David,
I am not a programmer in any sense, but know enough to be able to make a real mess. Anyway, is there a way to set the font from the .tex file instead of at the .sty level?

**Comment by davidcarlisle** [comment]
yes if you get the version from github



then you can set the font see test-tt-6.tex which has

\newcommand\ttbasefont{Press Gutenberg.ttf}% from
http://www.1001fonts.com/press-gutenberg-font.html

to use a Gutenberg(ish) style font and turns off all over-printing

**Comment by Shane-Brandes** [comment]
o.k. overlooked that. thanks! I guess we can close that issue.
