### ISSUE TITLE
tabulary should reset counters, like tabularx

### ISSUE THREAD

**Issue by davidcarlisle** [davidcarlisle/dpctex#12]
https://tex.stackexchange.com/a/119575

**Comment by yjyao** [comment]
I ran into this problem today and found your answer (i.e., your link in comment 1). This patch seems to be working but is not updated in [CTAN](https://ctan.org/pkg/tabulary). Do you have plans to update the CTAN package?

**Comment by davidcarlisle** [comment]
@yjyao  oh thanks for the reminder, I had no plans to update at ctan as I had forgotten completely about this. I'll see what I can do...

**Comment by davidcarlisle** [comment]
@yjyao  2018, doesn't time fly....

**Comment by davidcarlisle** [comment]
@yjyao  Version 0.11 implementing this has been submitted to ctan
