### ISSUE TITLE
colortbl: lost color when space is in \hhline

### ISSUE THREAD

**Issue by FrankMittelbach** [davidcarlisle/dpctex#25]
```

\documentclass{article}
\pagestyle{empty}
\usepackage{colortbl,hhline} \setlength\arrayrulewidth{1pt}
\begin{document}
\begin{tabular}{c|c|c}
\hline
 A  & B  & C  \\ \hhline{= >{\arrayrulecolor{blue}}==}
100 & 10 & 1  \\ \hhline{=>{\arrayrulecolor{blue}}==}
\end{tabular}
\end{document}
```
First \hhline is completely black.

<img width="672" alt="Screenshot 2020-01-15 at 19 58 49" src="https://user-images.githubusercontent.com/1062981/72462500-7e9afb00-37d1-11ea-8366-8ae48f72c4fb.png">

**Comment by davidcarlisle** [comment]
I think you are using the ctan version, it works OK if I use the version from here, I'll try and push it out this evening.

**Comment by FrankMittelbach** [comment]
indeed. I thought it was already on CTAN. so I can confirm the new version works for me
