### ISSUE TITLE
mylatex: \makeatletter is considered an undefined control sequence

### ISSUE THREAD

**Issue by matteocoder** [davidcarlisle/dpctex#28]
I was trying to use `mylatex`, but compilation stops right at the beginning returning an "Undefined control sequence l.126 \makeatletter" error.
Here is the mwe:
```
\documentclass{article}
\usepackage{fontspec}
\usepackage{lipsum,showframe}
\begin{document}
\lipsum
\end{document}
```
which I tried to compile using `lualatex -ini mylatex.ltx mwe`.
I tried compiling this on Windows 10 Home 64-bit 1909 with TeXLive 2020 updated on the 28th of October.

**Comment by davidcarlisle** [comment]
You need to load the lualatex format

```
lualatex -ini "&lualatex" mylatex.ltx mwe
```

**Comment by matteocoder** [comment]
@davidcarlisle Thank you for your reply.
