### ISSUE TITLE
[textcase] Accents in (e.g.) `\MakeTextLowercase` used to work but don't work anymore

### ISSUE THREAD

**Issue by dbitouze** [davidcarlisle/dpctex#31]
The following MCE:
```latex
\documentclass{article}
\usepackage{textcase}
\begin{document}
\MakeTextLowercase{Café}
\end{document}
```
used to compile (with `pdflatex`) like a charm with an up to date TL 2021 but, with an up to date TL 2022, that's not the case anymore:
```
! LaTeX Error: Invalid UTF-8 byte sequence (��\ifx).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.24 \MakeTextLowercase{Café}
```

**Comment by davidcarlisle** [comment]
You did not show your log but hopefully that error was not using the version from this repository, I get no error on your test and a log

```
Package: textcase 2022/06/12 v1.02 Text only upper/lower case changing (DPC)
```

that version went to ctan yesterday so should be in texlive today or tomorrow, see also

https://tex.stackexchange.com/questions/647525/maketextuppercase-broke-for-cyrillic#comment1613663_647525

**Comment by davidcarlisle** [comment]
You did not show your log but hopefully that error was not using the version from this repository, I get no error on your test and a log

```
Package: textcase 2022/06/12 v1.02 Text only upper/lower case changing (DPC)
```

that version went to ctan yesterday so should be in texlive today or tomorrow, see also

https://tex.stackexchange.com/questions/647525/maketextuppercase-broke-for-cyrillic#comment1613663_647525

**Comment by dbitouze** [comment]
> You did not show your log

Sorry. Here is my file list:
```
 *File List*
 article.cls    2021/10/04 v1.4n Standard LaTeX document class
  size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
textcase.sty    2019/09/14 v1.00 Text only upper/lower case changing (DPC)
l3backend-pdftex.def    2022-04-20 L3 backend support: PDF output (pdfTeX)
 ***********
```

> but hopefully that error was not using the version from this repository, I get no error on your test and a log
> 
> ```
> Package: textcase 2022/06/12 v1.02 Text only upper/lower case changing (DPC)
> ```
> 
> that version went to ctan yesterday so should be in texlive today or tomorrow, see also

Good news! Thanks!

> https://tex.stackexchange.com/questions/647525/maketextuppercase-broke-for-cyrillic#comment1613663_647525

OK. As advised, I rely now on `\MakeLowercase` instead of `\MakeTextLowercase`.
