### ISSUE TITLE
adding rownum to colortbl

### ISSUE THREAD

**Issue by davidcarlisle** [davidcarlisle/dpctex#34]
commit c66feb4e64d82e24e9f37488bfdc3f698d65926e adds a LaTeX counter alias so `\roman{rownum}` works like `\romannumeral\rownum`  in the `\rownum` code imported from `xcolor`

The xcolor code only activates `\rownum`  if  `\rowcolors`  is active which may have made sense to minimise the `xcolor` patch but feels wrong here, I have modifed the test file base result in that commit so it shows row 3 as III even without colors (so the test currently fails as this is not implemented)

@lvjr If this causes you problems please comment here. There is no rush to release anything to ctan so we can adjust things to avoid clashes.

**Comment by lvjr** [comment]
@davidcarlisle So far so good, with the latest code of `colortbl` and `tabularray`.

**Comment by davidcarlisle** [comment]
@lvjr  thanks for checking.

I want to adjust things a bit more so the rowum counter gets incremented more naturally, not just if rows are being coloured but that should be internal code here not affecting you. If I adjust the declaration of the row counter I'll ping you again, also I will give you notice before a ctan release just in case (it will not be this week).

**Comment by lvjr** [comment]
I have uploaded a new release of `tabularray` to CTAN to push other updates to users. Since the only change to `\c@rownum` counter is replacing `\int_new:N` with `\int_zero_new:N`, I think it is safe to publish the release. And if further changes to `\c@rownum` are needed I can upload another new release later.
