### ISSUE TITLE
apparent typo in bm doc

### ISSUE THREAD

**Issue by jfbu** [davidcarlisle/dpctex#45]
Hi, the bm doc (v1.2f, last revised 2023/07/08) says

```
In the fourth example the \mathrm{\bm{g}} is essentially equivalent to \mathrm{\mbox{\boldmath$g$}}
```

on page 3.  I believe what is intended has an extra `{}` around the `g`

```
In the fourth example the \mathrm{\bm{{g}}} is essentially equivalent to \mathrm{\mbox{\boldmath$g$}}
```

The casual reader will have had difficulties tor reconcile the sentence without extra `{}` about the example 4 as above with the description of example 2 behaviour.

**Comment by davidcarlisle** [comment]
er yes thanks 

probably this would be better raised on latex2e issue for the latex2e/required/tools version. The version here is for some rather more speculative changes to better support unicode tex and has never been released to ctan. But it doesn't really matter, I'll fix  in both places anyway.

> The casual reader will have had difficulties tor reconcile the sentence without extra {}

You are just being polite, you could simply have said "the documentation is wrong" :-)

**Comment by jfbu** [comment]
> You are just being polite, you could simply have said "the documentation is wrong" :-)

I was too shy to point out for how many decades it has been so, probably ;-)

And sorry for wrong issue tracker, I <s>figured</s> *assumed* the page 1 link to https://latex-project.org/bugs.html was obsolete but I should have read more closely the mention of "category tools".
