### ISSUE TITLE
Justifying Option

### ISSUE THREAD

**Issue by rafa-cc** [davidcarlisle/dpctex#49]
I'd like to keep de whole variability in grey level and angle of each character but with the option of justified text

**Comment by davidcarlisle** [comment]
sorry I have no idea what this refers to, If you have an issue please state which package you are writing about (there are around 20 latex packages in this dpctex repo)   and include a small test file showing the issue. I'll close but it can be re-opened if any information is added,

**Comment by rafa-cc** [comment]
ou sorry i forgot it. I am referring to the "typewriter" package i know it's designed to imitate the style of typewriters which had no way of justifying the text; more than a request I'd like to have a guide on how to obtain the justified text, because using ragged2e doesn't work:

```
\documentclass[letterpaper, 10pt]{article}

\usepackage[top = 3cm, bottom = 2.5 cm, left = 2.5 cm, right = 2.5 cm]{geometry}
\setlength{\parindent}{0cm}

\usepackage{typewriter}
\usepackage{ragged2e}
\usepackage{lipsum}
\begin{document}
\justifying
\lipsum

\end{document}
```

**Comment by davidcarlisle** [comment]
I don't think there are any circumstances when `\justifying` is ever needed in any document. Justification is the latex default.  `typewriter` does nothing to disable justifcation, it is just using a tt font so as usual it has fixed width spaces and no hyphenation so justification can not produce even margins, if you specify a proportional font then the justification can produce an effect.

![image](https://github.com/davidcarlisle/dpctex/assets/1268738/0793ebbd-2f24-4643-8046-bc5098408814)


```
\documentclass[letterpaper, 10pt]{article}

\usepackage[top = 3cm, bottom = 2.5 cm, left = 2.5 cm, right = 2.5 cm]{geometry}
\setlength{\parindent}{0cm}

\providecommand\ttbasefont{texgyreheros-regular.otf}

\usepackage{typewriter}

\usepackage{lipsum}
\begin{document}

\lipsum

\end{document}
```

**Comment by rafa-cc** [comment]
wow it was that simple, I appreciate a lot your guide, thanks
