### ISSUE TITLE
Mathml xmt file

### ISSUE THREAD

**Issue by balakrishnan1978** [davidcarlisle/dpctex#5]
Dear David,

Thanks for provided XML supported latex package and could you have latest all mathml supported xmt file?

**Comment by davidcarlisle** [comment]
I am not sure what you are asking for here, the last versions of all the
xmltex files are here in this github repository.
(Personally I wouln't use xmltex, I would convert the xml to tex syntax
using xslt and use normal tex packages)

david

**Comment by balakrishnan1978** [comment]
Dear David,

I am new in GitHub and could you please provide the link updated files in GitHub please.

**Comment by davidcarlisle** [comment]
The files have not been updated for a decade or so but they are here

https://github.com/davidcarlisle/dpctex/tree/master/xmltex/base

**Comment by balakrishnan1978** [comment]
Could you please provide all the mathml coding defined xmt (mathml.xmt) file please?

**Comment by davidcarlisle** [comment]
I am sorry but you asked exactly the same thing before and I really do not know what it is that you are asking for. _Everything_ that I have related to this project is freely downloadable from this site. I do not have anything else to give.
